#
#test workflow ACR

name: Docker Image CI

on: [push]

jobs:


  build:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Azure Container Registry
      run: docker login -u Github-actions -p ${{ secrets.ACR_TOKEN }} dataregestry.azurecr.io

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: dataregestry.azurecr.io/wine-model:v0.3


    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id:
        tenant-id:
        subscription-id:

    - name: Deploy to Azure Container App
      uses: azure/aci-deploy@v1
      with:
        resource_group: data
        container_name: wine-model
        image: dataregestry.azurecr.io/wine-model:v0.3
        registry_login_server: dataregestry.azurecr.io
        registry_username: ${{ secrets.ACR_USERNAME }}
        registry_password: ${{ secrets.ACR_TOKEN }}
        location: West US 2
