#docker login -u Github-actions -p uvi40H/B3AL6y8Be4ztErlf5H5IGikMYcGRs9171xl+ACRDhoK4B dataregestry.azurecr.io
#test workflow ACR

name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Azure Container Registry
      uses: docker/login-action@v1 
      with:
        registry: dataregestry.azurecr.io
        username: Github-actions
        password: ${{ secrets.ACR_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: dataregestry.azurecr.io/wine-model:v0.3
