#
#test workflow ACR

name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Echo secret -
      run: echo " ${{ secrets.ACR-TOKEN }}"

    - name: Echo secret _
      run: echo " se_:${{ secrets.ACR_TOKEN }}"

    - name: Login to Azure Container Registry
      run: docker login -u Github-actions -p ${{ secrets.ACR-TOKEN }} dataregestry.azurecr.io

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: dataregestry.azurecr.io/wine-model:v0.3
